### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by zenorocha** [olivernn/canvas.fm#2]
How can I run it? I tried to run the command `node app.js` on the root directory of canvas.fm but nothing happened =/

**Comment by olivernn** [comment]
That works for me on my machine.  What exactly happens when you run `node app.js`, is there any response at all?  You should see `Fri, 04 May 2012 08:48:24 GMT 'Canvas.fm starting'` and then the app should be available on port 3000.

What version of node are you running?

**Comment by zenorocha** [comment]
When I run: `node app.js`

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'express'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/zeno/Playground/projetos pessoais/canvasfm/app.js:1:77)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)`
```

It seems like I need to install `express`, but when I try to install it: `npm install express`

```
npm http GET https://registry.npmjs.org/express/2.4.7
npm http 304 https://registry.npmjs.org/express/2.4.7

npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: express@2.4.7
npm ERR! Required: {"node":">= 0.4.1 < 0.5.0"}
npm ERR! Actual:   {"npm":"1.1.12","node":"0.6.14"}
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/Users/zeno/nvm/v0.6.14/bin/npm" "install" "express"
npm ERR! cwd /Users/zeno/Playground/projetos pessoais/canvasfm
npm ERR! node -v v0.6.14
npm ERR! npm -v 1.1.12
npm ERR! code ENOTSUP
npm ERR! message Unsupported
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/zeno/Playground/projetos pessoais/canvasfm/npm-debug.log
npm not ok
```

I'm using node version `v0.6.14`, but I understand that I need an older version of Node, so I used [nvm](https://github.com/creationix/nvm) to install it: `nvm install v0.4.1` then `nvm use v0.4.1`.

So I try to install `express` again: `npm install express`

```
Error: npm doesn't work with node v0.4.1
Required: node@0.6 || 0.7 || 0.8
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:60:23
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:80:2)
    at Module._compile (module.js:374:26)
    at Object..js (module.js:380:10)
    at Module.load (module.js:306:31)
    at Function._load (module.js:272:10)
    at Array.0 (module.js:393:10)
    at EventEmitter._tickCallback (node.js:108:26)
```

I don't know what do anymore and I'm really interested in run it.

**Comment by olivernn** [comment]
I'm currently using node v0.6.2.

You should be able to install all the dependencies required for the application to start by running `npm install .` inside the canvas.fm directory.

I'm not sure if anything has changed between 0.6.2 and 0.6.14 of node that would introduce huge backwards compatibility issues.  I'm not so sure about the express dependency though, currently the package.json file just specifies the 2.x.x branch.

Taking a closer look I am running version 2.5.8 of express, which according to the package.json file for it says that it should work on all v0.6 of node.

Try the `npm install .` and let me know if you are still having issues.

**Comment by zenorocha** [comment]
I'm using node v.0.6.2 but my problem with express still the same =/

```
Zeno:canvasfm zeno$ node -v
v0.6.2
Zeno:canvasfm zeno$ npm install .
npm http GET https://registry.npmjs.org/express/2.4.7
npm http GET https://registry.npmjs.org/mysql/0.9.3
npm http GET https://registry.npmjs.org/connect-form/0.2.1
npm http 304 https://registry.npmjs.org/mysql/0.9.3
npm http 304 https://registry.npmjs.org/express/2.4.7
npm http 304 https://registry.npmjs.org/connect-form/0.2.1

npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: express@2.4.7
npm ERR! Required: {"node":">= 0.4.1 < 0.5.0"}
npm ERR! Actual:   {"npm":"1.1.0-2","node":"0.6.2"}
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "."
npm ERR! cwd /Users/zeno/Playground/projetos pessoais/canvasfm
npm ERR! node -v v0.6.2
npm ERR! npm -v 1.1.0-2
npm ERR! code ENOTSUP
npm ERR! message Unsupported
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/zeno/Playground/projetos pessoais/canvasfm/npm-debug.log
npm not ok
```

**Comment by olivernn** [comment]
Thats odd, @visionmedia any clues?  I can confirm that express is working for me locally with this version of node.

**Comment by tj** [comment]
you should be able to update to 2.5.9 without trouble
